In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
import nltk
import spacy

In [3]:
textfiledata=pd.read_csv(r"C:\Users\ggomare\Downloads\Comments.csv")

In [4]:
textfiledata

        ID                                           Comments
0     1309  Does not like the way the phone works. It is t...
1     3556  Wanted to know the nearest store location. Wan...
2     2230  Wants to know how to do text messaging. Referr...
3     2312  Asked how to disable call waiting. referred hi...
4     3327  Needs help learning how to use the phone. I su...
...    ...                                                ...
2065  3034  Needed help figuring out his bill. I explained...
2066   271  He lost his phone and called to cancel service...
2067   783  Lost the directions to phone and wants another...
2068  1295                           Wants to change address.
2069  1807  He lost his phone and called to cancel service...

[2070 rows x 2 columns]

In [5]:
from nltk.tokenize import word_tokenize

In [6]:
nltk.download('punkt')
textfiledata["CommentsTokenized"]=textfiledata['Comments'].apply(word_tokenize)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ggomare\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [7]:
textfiledata

,ID,Comments,CommentsTokenized
0,1309,Does not like the way the phone works. It is t...,"[Does, not, like, the, way, the, phone, works,..."
1,3556,Wanted to know the nearest store location. Wan...,"[Wanted, to, know, the, nearest, store, locati..."
2,2230,Wants to know how to do text messaging. Referr...,"[Wants, to, know, how, to, do, text, messaging..."
3,2312,Asked how to disable call waiting. referred hi...,"[Asked, how, to, disable, call, waiting, ., re..."
4,3327,Needs help learning how to use the phone. I su...,"[Needs, help, learning, how, to, use, the, pho..."
...,...,...,...
2065,3034,Needed help figuring out his bill. I explained...,"[Needed, help, figuring, out, his, bill, ., I,..."
2066,271,He lost his phone and called to cancel service...,"[He, lost, his, phone, and, called, to, cancel..."
2067,783,Lost the directions to phone and wants another...,"[Lost, the, directions, to, phone, and, wants,..."
2068,1295,Wants to change address.,"[Wants, to, change, address, .]"
2069,1807,He lost his phone and called to cancel service...,"[He, lost, his, phone, and, called, to, cancel..."

# First Stemmer: PorterStemmer

In [8]:
from nltk.stem import PorterStemmer

In [9]:
setmmer=PorterStemmer()

In [10]:
textfiledata1=textfiledata.drop(columns=["Comments","CommentsTokenized"])

In [11]:
textfiledata1["CommentsTokenizedStemmed"]=textfiledata["CommentsTokenized"].apply(lambda x: [setmmer.stem(y) for y in x])

In [12]:
textfiledata1

        ID                           CommentsTokenizedStemmed
0     1309  [doe, not, like, the, way, the, phone, work, ....
1     3556  [want, to, know, the, nearest, store, locat, ....
2     2230  [want, to, know, how, to, do, text, messag, .,...
3     2312  [ask, how, to, disabl, call, wait, ., refer, h...
4     3327  [need, help, learn, how, to, use, the, phone, ...
...    ...                                                ...
2065  3034  [need, help, figur, out, hi, bill, ., i, expla...
2066   271  [he, lost, hi, phone, and, call, to, cancel, s...
2067   783  [lost, the, direct, to, phone, and, want, anot...
2068  1295                      [want, to, chang, address, .]
2069  1807  [he, lost, hi, phone, and, call, to, cancel, s...

[2070 rows x 2 columns]

# Second Stemmer: SnowballStemmer

In [13]:
from nltk.stem.snowball import SnowballStemmer

In [14]:
stemmer2=SnowballStemmer("english")

In [15]:
textfiledata2=textfiledata.drop(columns=["Comments","CommentsTokenized"])
textfiledata2["CommentsTokenizedStemmed"]=textfiledata["CommentsTokenized"].apply(lambda x: [stemmer2.stem(y) for y in x])

In [16]:
textfiledata2

        ID                           CommentsTokenizedStemmed
0     1309  [doe, not, like, the, way, the, phone, work, ....
1     3556  [want, to, know, the, nearest, store, locat, ....
2     2230  [want, to, know, how, to, do, text, messag, .,...
3     2312  [ask, how, to, disabl, call, wait, ., refer, h...
4     3327  [need, help, learn, how, to, use, the, phone, ...
...    ...                                                ...
2065  3034  [need, help, figur, out, his, bill, ., i, expl...
2066   271  [he, lost, his, phone, and, call, to, cancel, ...
2067   783  [lost, the, direct, to, phone, and, want, anot...
2068  1295                      [want, to, chang, address, .]
2069  1807  [he, lost, his, phone, and, call, to, cancel, ...

[2070 rows x 2 columns]

In [17]:
from nltk.stem import LancasterStemmer

In [18]:
stemmer3=LancasterStemmer()

In [19]:
textfiledata3=textfiledata.drop(columns=["Comments","CommentsTokenized"])
textfiledata3["CommentsTokenizedStemmed"]=textfiledata["CommentsTokenized"].apply(lambda x: [stemmer3.stem(y) for y in x])

In [20]:
textfiledata3

        ID                           CommentsTokenizedStemmed
0     1309  [doe, not, lik, the, way, the, phon, work, ., ...
1     3556  [want, to, know, the, nearest, stor, loc, ., w...
2     2230  [want, to, know, how, to, do, text, mess, ., r...
3     2312  [ask, how, to, dis, cal, wait, ., refer, him, ...
4     3327  [nee, help, learn, how, to, us, the, phon, ., ...
...    ...                                                ...
2065  3034  [nee, help, fig, out, his, bil, ., i, explain,...
2066   271  [he, lost, his, phon, and, cal, to, cancel, se...
2067   783  [lost, the, direct, to, phon, and, want, anoth...
2068  1295                      [want, to, chang, address, .]
2069  1807  [he, lost, his, phon, and, cal, to, cancel, se...

[2070 rows x 2 columns]

# Lemmatization

In [21]:
nltk.download('wordnet')
nltk.download('omw-1.4')
from nltk import WordNetLemmatizer

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\ggomare\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\ggomare\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

In [22]:
lemma=WordNetLemmatizer()

In [23]:
textfiledata4=textfiledata.drop(columns=["Comments","CommentsTokenized"])
textfiledata4["CommentsTokenizedStemmed"]=textfiledata["CommentsTokenized"].apply(lambda x:[lemma.lemmatize(y) for y in x])

In [24]:
textfiledata4

        ID                           CommentsTokenizedStemmed
0     1309  [Does, not, like, the, way, the, phone, work, ...
1     3556  [Wanted, to, know, the, nearest, store, locati...
2     2230  [Wants, to, know, how, to, do, text, messaging...
3     2312  [Asked, how, to, disable, call, waiting, ., re...
4     3327  [Needs, help, learning, how, to, use, the, pho...
...    ...                                                ...
2065  3034  [Needed, help, figuring, out, his, bill, ., I,...
2066   271  [He, lost, his, phone, and, called, to, cancel...
2067   783  [Lost, the, direction, to, phone, and, want, a...
2068  1295                    [Wants, to, change, address, .]
2069  1807  [He, lost, his, phone, and, called, to, cancel...

[2070 rows x 2 columns]

In [69]:
nlp=spacy.load("en_core_web_sm")
doc=nlp(textfiledata["CommentsTokenized"])
# for token in doc:
#     print(token,"|",token.lemma_)

ValueError: [E1041] Expected a string, Doc, or bytes as input, but got: <class 'pandas.core.series.Series'>

In [70]:
textfiledata1['CommentsTokenizedStemmed'] = textfiledata1['CommentsTokenizedStemmed'].apply(lambda x: " ".join(x))

In [71]:
textfiledata1

        ID                           CommentsTokenizedStemmed
0     1309  doe not like the way the phone work . it is to...
1     3556  want to know the nearest store locat . want to...
2     2230  want to know how to do text messag . refer him...
3     2312  ask how to disabl call wait . refer him to web...
4     3327  need help learn how to use the phone . i sugge...
...    ...                                                ...
2065  3034  need help figur out hi bill . i explain our mi...
2066   271  he lost hi phone and call to cancel servic . i...
2067   783  lost the direct to phone and want anoth manual...
2068  1295                            want to chang address .
2069  1807  he lost hi phone and call to cancel servic . i...

[2070 rows x 2 columns]

In [72]:
from sklearn.feature_extraction.text import CountVectorizer
count_vecto=CountVectorizer(stop_words='english',lowercase=False)

In [73]:
TD_counts=count_vecto.fit_transform(textfiledata1.CommentsTokenizedStemmed)

In [74]:
TD_counts.shape

(2070, 358)

In [75]:
DF_TD_Counts=pd.DataFrame(TD_counts.toarray())

In [76]:
DF_TD_Counts

,0,1,2,3,4,5,6,7,8,9,...,348,349,350,351,352,353,354,355,356,357
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2065,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2066,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2067,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2068,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
2069,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [77]:
from sklearn.feature_extraction.text import TfidfTransformer

In [78]:
tf_idf=TfidfTransformer()
X_train_tfidf = tf_idf.fit_transform(TD_counts)

In [79]:
X_train_tfidf

<2070x358 sparse matrix of type '<class 'numpy.float64'>'
	with 16681 stored elements in Compressed Sparse Row format>

In [80]:
DF_TF_IDF=pd.DataFrame(X_train_tfidf.toarray())

In [81]:
DF_TF_IDF

,0,1,2,3,4,5,6,7,8,9,...,348,349,350,351,352,353,354,355,356,357
0,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.206947,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.27568,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2065,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
2066,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
2067,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
2068,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.772949,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0
2069,0.0,0.0,0.0,0.0,0.00000,0.0,0.0,0.0,0.0,0.000000,...,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0

In [82]:
customer_data=pd.read_csv(r"C:\Users\ggomare\Downloads\Customers.csv")

In [83]:
Y_train=customer_data["TARGET"]

In [84]:
from sklearn.feature_selection import SelectKBest

In [85]:
select=SelectKBest(k=30)

In [86]:
new_df_tf_idf=select.fit_transform(DF_TF_IDF,Y_train)

In [87]:
new_df_tf_idf_selected=pd.DataFrame(new_df_tf_idf)

In [88]:
new_df_tf_idf_selected

,0,1,2,3,4,5,6,7,8,9,...,20,21,22,23,24,25,26,27,28,29
0,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2065,0.0,0.0,0.000000,0.432087,0.0,0.0,0.0,0.0,0.445599,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2066,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2067,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2068,0.0,0.0,0.545354,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2069,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.000000,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [89]:
select.get_support(indices=True)

array([ 14,  35,  49,  50,  51,  62,  70,  81, 115, 118, 121, 130, 189,
       193, 215, 220, 224, 225, 238, 242, 247, 251, 252, 257, 262, 276,
       311, 317, 323, 346], dtype=int64)

In [90]:
from sklearn.metrics import confusion_matrix, classification_report

In [91]:
from sklearn.model_selection import cross_val_score

In [92]:
from sklearn.ensemble import RandomForestClassifier

In [93]:
model=RandomForestClassifier()

In [94]:
model.fit(new_df_tf_idf_selected,Y_train)

RandomForestClassifier()

In [95]:
pred=model.predict(new_df_tf_idf_selected)

In [96]:
print(classification_report(pred,Y_train))

              precision    recall  f1-score   support

   Cancelled       0.08      0.73      0.14        83
     Current       0.98      0.63      0.76      1987

    accuracy                           0.63      2070
   macro avg       0.53      0.68      0.45      2070
weighted avg       0.95      0.63      0.74      2070

In [97]:
from sklearn.model_selection import cross_val_score

In [98]:
score=cross_val_score(model,new_df_tf_idf_selected,Y_train,cv=9,scoring="balanced_accuracy")

In [99]:
score

array([0.50833333, 0.5281746 , 0.51349206, 0.52279066, 0.53844928,
       0.52159535, 0.52099769, 0.53016177, 0.50119531])

In [100]:
score.mean()

0.5205766727760512

In [101]:
customer_data

,ID,Sex,Status,Children,Est_Income,Car_Owner,Usage,Age,RatePlan,LongDistance,International,Local,Dropped,Paymethod,LocalBilltype,LongDistanceBilltype,TARGET
0,1,F,S,1,38000.00,N,229.64,24.393333,3,23.56,0.00,206.08,0,CC,Budget,Intnl_discount,Cancelled
1,6,M,M,2,29616.00,N,75.29,49.426667,2,29.78,0.00,45.50,0,CH,FreeLocal,Standard,Current
2,8,M,M,0,19732.80,N,47.25,50.673333,3,24.81,0.00,22.44,0,CC,FreeLocal,Standard,Current
3,11,M,S,2,96.33,N,59.01,56.473333,1,26.13,0.00,32.88,1,CC,Budget,Standard,Current
4,14,F,M,2,52004.80,N,28.14,25.140000,1,5.03,0.00,23.11,0,CH,Budget,Intnl_discount,Cancelled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2065,3821,F,S,0,78851.30,N,29.04,48.373333,4,0.37,0.00,28.66,0,CC,FreeLocal,Standard,Cancelled
2066,3822,F,S,1,17540.70,Y,36.20,62.786667,1,22.17,0.57,13.45,0,Auto,Budget,Standard,Cancelled
2067,3823,F,M,0,83891.90,Y,74.40,61.020000,4,28.92,0.00,45.47,0,CH,Budget,Standard,Cancelled
2068,3824,F,M,2,28220.80,N,38.95,38.766667,4,26.49,0.00,12.46,0,CC,FreeLocal,Standard,Cancelled
2069,3825,F,S,0,28589.10,N,100.28,15.600000,3,13.19,0.00,87.09,0,CC,FreeLocal,Standard,Cancelled

In [102]:
customer_data["Sex"].unique()

array(['F', 'M'], dtype=object)

In [103]:
customer_data["Sex"].replace({
    'F':0,
    'M':1
},inplace=True)

In [104]:
customer_data["Status"].unique()

array(['S', 'M', 'D'], dtype=object)

In [105]:
customer_data["Status"].replace({
    'S':1, 'M':1, 'D':2
},inplace=True)

In [106]:
customer_data["Car_Owner"].unique()

array(['N', 'Y'], dtype=object)

In [107]:
customer_data["Car_Owner"].replace({
    'N':0, 'Y':1},
inplace=True)

In [108]:
customer_data["Paymethod"].unique()

array(['CC', 'CH', 'Auto'], dtype=object)

In [109]:
customer_data["Paymethod"].replace({
    'CC':1, 'CH':2, 'Auto':3
},inplace=True)

In [110]:
customer_data["LocalBilltype"].unique()

array(['Budget', 'FreeLocal'], dtype=object)

In [111]:
customer_data["LocalBilltype"].replace({
   'Budget':1, 'FreeLocal':2 
},inplace=True)

In [112]:
customer_data["LongDistanceBilltype"].unique()

array(['Intnl_discount', 'Standard'], dtype=object)

In [113]:
customer_data["LongDistanceBilltype"].replace({
   'Intnl_discount':1, 'Standard':2 
},inplace=True)

In [114]:
customer_data

,ID,Sex,Status,Children,Est_Income,Car_Owner,Usage,Age,RatePlan,LongDistance,International,Local,Dropped,Paymethod,LocalBilltype,LongDistanceBilltype,TARGET
0,1,0,1,1,38000.00,0,229.64,24.393333,3,23.56,0.00,206.08,0,1,1,1,Cancelled
1,6,1,1,2,29616.00,0,75.29,49.426667,2,29.78,0.00,45.50,0,2,2,2,Current
2,8,1,1,0,19732.80,0,47.25,50.673333,3,24.81,0.00,22.44,0,1,2,2,Current
3,11,1,1,2,96.33,0,59.01,56.473333,1,26.13,0.00,32.88,1,1,1,2,Current
4,14,0,1,2,52004.80,0,28.14,25.140000,1,5.03,0.00,23.11,0,2,1,1,Cancelled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2065,3821,0,1,0,78851.30,0,29.04,48.373333,4,0.37,0.00,28.66,0,1,2,2,Cancelled
2066,3822,0,1,1,17540.70,1,36.20,62.786667,1,22.17,0.57,13.45,0,3,1,2,Cancelled
2067,3823,0,1,0,83891.90,1,74.40,61.020000,4,28.92,0.00,45.47,0,2,1,2,Cancelled
2068,3824,0,1,2,28220.80,0,38.95,38.766667,4,26.49,0.00,12.46,0,1,2,2,Cancelled
2069,3825,0,1,0,28589.10,0,100.28,15.600000,3,13.19,0.00,87.09,0,1,2,2,Cancelled

In [115]:
X_train=customer_data.drop(columns="TARGET")

In [116]:
X_train

,ID,Sex,Status,Children,Est_Income,Car_Owner,Usage,Age,RatePlan,LongDistance,International,Local,Dropped,Paymethod,LocalBilltype,LongDistanceBilltype
0,1,0,1,1,38000.00,0,229.64,24.393333,3,23.56,0.00,206.08,0,1,1,1
1,6,1,1,2,29616.00,0,75.29,49.426667,2,29.78,0.00,45.50,0,2,2,2
2,8,1,1,0,19732.80,0,47.25,50.673333,3,24.81,0.00,22.44,0,1,2,2
3,11,1,1,2,96.33,0,59.01,56.473333,1,26.13,0.00,32.88,1,1,1,2
4,14,0,1,2,52004.80,0,28.14,25.140000,1,5.03,0.00,23.11,0,2,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2065,3821,0,1,0,78851.30,0,29.04,48.373333,4,0.37,0.00,28.66,0,1,2,2
2066,3822,0,1,1,17540.70,1,36.20,62.786667,1,22.17,0.57,13.45,0,3,1,2
2067,3823,0,1,0,83891.90,1,74.40,61.020000,4,28.92,0.00,45.47,0,2,1,2
2068,3824,0,1,2,28220.80,0,38.95,38.766667,4,26.49,0.00,12.46,0,1,2,2
2069,3825,0,1,0,28589.10,0,100.28,15.600000,3,13.19,0.00,87.09,0,1,2,2

In [117]:
model.fit(X_train,Y_train)

RandomForestClassifier()

In [118]:
pred=model.predict(X_train)

In [119]:
print(classification_report(pred,Y_train))

              precision    recall  f1-score   support

   Cancelled       1.00      1.00      1.00       804
     Current       1.00      1.00      1.00      1266

    accuracy                           1.00      2070
   macro avg       1.00      1.00      1.00      2070
weighted avg       1.00      1.00      1.00      2070

In [120]:
from collections import Counter

In [121]:
Counter(Y_train)

Counter({'Cancelled': 804, 'Current': 1266})

In [122]:
confusion_matrix(pred,Y_train)

array([[ 804,    0],
       [   0, 1266]], dtype=int64)

In [123]:
from sklearn.model_selection import train_test_split

In [124]:
from sklearn.tree import DecisionTreeClassifier
model1=DecisionTreeClassifier()

In [125]:
xtrain,xtest,ytrain,ytest=train_test_split(X_train,Y_train,test_size=0.25)

In [126]:
model1.fit(xtrain,ytrain)

DecisionTreeClassifier()

In [127]:
model1.score(xtest,ytest)

0.8243243243243243

In [128]:
pred1=model1.predict(xtest)

In [129]:
print(classification_report(pred1,ytest))

              precision    recall  f1-score   support

   Cancelled       0.77      0.78      0.78       202
     Current       0.86      0.85      0.86       316

    accuracy                           0.82       518
   macro avg       0.82      0.82      0.82       518
weighted avg       0.82      0.82      0.82       518

In [130]:
DF_TF_IDF['ID']=textfiledata['ID']

In [131]:
combined_cust_comm=pd.merge(X_train,DF_TF_IDF,on='ID')

In [132]:
combined_cust_comm.shape

(2070, 374)

In [133]:
Cxtrain,Cxtest,Cytrain,Cytest=train_test_split(combined_cust_comm,Y_train,test_size=0.25)

In [134]:
model.fit(Cxtrain,Cytrain)

RandomForestClassifier()

In [135]:
pred2=model.predict(Cxtest)

In [136]:
print(classification_report(pred2,Cytest))

              precision    recall  f1-score   support

   Cancelled       0.90      0.84      0.87       203
     Current       0.90      0.94      0.92       315

    accuracy                           0.90       518
   macro avg       0.90      0.89      0.89       518
weighted avg       0.90      0.90      0.90       518

In [137]:
confusion_matrix(pred2,Cytest)

array([[171,  32],
       [ 20, 295]], dtype=int64)

In [138]:
model3=DecisionTreeClassifier()

In [139]:
model3.fit(Cxtrain,Cytrain)

DecisionTreeClassifier()

In [140]:
model3.feature_importances_

array([0.15064639, 0.01694596, 0.00368932, 0.11535545, 0.08761692,
       0.00586975, 0.01901829, 0.05013514, 0.0583197 , 0.0957286 ,
       0.        , 0.00271875, 0.00996957, 0.0631783 , 0.0057296 ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.00027967, 0.        , 0.        ,
       0.        , 0.00238525, 0.        , 0.        , 0.00078126,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.01625334, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.0005594 , 0.        , 0.        ,
       0.00134814, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.00677976, 0.00179752,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.00490875, 0.        , 0.        , 0.        ,
       0.        , 0.01532787, 0.        , 0.        , 0.00062663,
       0.        , 0.        , 0.00397562, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.00019379,
       0.00114528, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.00269628, 0.        ,
       0.        , 0.        , 0.        , 0.00076712, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.00331273, 0.        , 0.        ,
       0.04171545, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.00415998,
       0.        , 0.        , 0.        , 0.016835  , 0.00046666,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.01399702, 0.        ,
       0.        , 0.0073594 , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.01633376, 0.        , 0.        , 0.        , 0.0003527 ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.11383375, 0.        , 0.        , 0.        ,
       0.        , 0.00315842, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.00156347,
       0.        , 0.02664822, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.00114074, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.00337036, 0.        , 0.        , 0.        , 0.00070661,
       0.        , 0.        , 0.        , 0.0002983 , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        ])

In [141]:
from sklearn.feature_selection import SelectFromModel

In [142]:
model1 = SelectFromModel(model3, prefit=True, max_features=20, threshold=-np.inf)
X_new= model1.transform(combined_cust_comm)
X_new_SelectedFeatures= pd.DataFrame(X_new)

In [143]:
X_new_SelectedFeatures

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,1.0,0.0,1.0,38000.00,229.64,24.393333,3.0,23.56,0.0,1.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.00000,0.000000,0.0
1,6.0,1.0,2.0,29616.00,75.29,49.426667,2.0,29.78,0.0,2.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.00000,0.271105,0.0
2,8.0,1.0,0.0,19732.80,47.25,50.673333,3.0,24.81,0.0,1.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.00000,0.271105,0.0
3,11.0,1.0,2.0,96.33,59.01,56.473333,1.0,26.13,1.0,1.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.00000,0.271105,0.0
4,14.0,0.0,2.0,52004.80,28.14,25.140000,1.0,5.03,0.0,2.0,0.000000,0.0,0.0,0.000000,0.0,0.0,0.0,0.00000,0.271105,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2065,3821.0,0.0,0.0,78851.30,29.04,48.373333,4.0,0.37,0.0,1.0,0.411182,0.0,0.0,0.325543,0.0,0.0,0.0,0.39978,0.000000,0.0
2066,3822.0,0.0,1.0,17540.70,36.20,62.786667,1.0,22.17,0.0,3.0,0.411182,0.0,0.0,0.325543,0.0,0.0,0.0,0.39978,0.000000,0.0
2067,3823.0,0.0,0.0,83891.90,74.40,61.020000,4.0,28.92,0.0,2.0,0.411182,0.0,0.0,0.325543,0.0,0.0,0.0,0.39978,0.000000,0.0
2068,3824.0,0.0,2.0,28220.80,38.95,38.766667,4.0,26.49,0.0,1.0,0.411182,0.0,0.0,0.325543,0.0,0.0,0.0,0.39978,0.000000,0.0
2069,3825.0,0.0,0.0,28589.10,100.28,15.600000,3.0,13.19,0.0,1.0,0.411182,0.0,0.0,0.325543,0.0,0.0,0.0,0.39978,0.000000,0.0

In [144]:
Fxtrain,Fxtest,Fytrain,Fytest=train_test_split(X_new_SelectedFeatures,Y_train,test_size=0.25)

In [145]:
model4=RandomForestClassifier()

In [146]:
model4.fit(Fxtrain,Fytrain)

RandomForestClassifier()

In [147]:
pred4=model4.predict(Fxtest)

In [148]:
print(classification_report(Fytest,pred4))

              precision    recall  f1-score   support

   Cancelled       0.87      0.84      0.86       201
     Current       0.90      0.92      0.91       317

    accuracy                           0.89       518
   macro avg       0.89      0.88      0.88       518
weighted avg       0.89      0.89      0.89       518

# Question 2

In [149]:
traindataset2=pd.read_csv(r"C:\Users\ggomare\Downloads\santander-customer-satisfaction\train.csv")

In [150]:
testdataset2=pd.read_csv(r"C:\Users\ggomare\Downloads\santander-customer-satisfaction\test.csv")

In [151]:
traindataset2.shape

(76020, 371)

In [152]:
testdataset2.shape

(75818, 370)

In [153]:
testdataset2

,ID,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var40_comer_ult1,imp_op_var40_comer_ult3,imp_op_var40_efect_ult1,imp_op_var40_efect_ult3,...,saldo_medio_var29_ult3,saldo_medio_var33_hace2,saldo_medio_var33_hace3,saldo_medio_var33_ult1,saldo_medio_var33_ult3,saldo_medio_var44_hace2,saldo_medio_var44_hace3,saldo_medio_var44_ult1,saldo_medio_var44_ult3,var38
0,2,2,32,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40532.100000
1,5,2,35,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,45486.720000
2,6,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46993.950000
3,7,2,24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,187898.610000
4,9,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,73649.730000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75813,151831,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,40243.200000
75814,151832,2,26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,146961.300000
75815,151833,2,24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,167299.770000
75816,151834,2,40,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117310.979016
75817,151837,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117310.979016

In [154]:
traindataset2

,ID,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var40_comer_ult1,imp_op_var40_comer_ult3,imp_op_var40_efect_ult1,imp_op_var40_efect_ult3,...,saldo_medio_var33_hace2,saldo_medio_var33_hace3,saldo_medio_var33_ult1,saldo_medio_var33_ult3,saldo_medio_var44_hace2,saldo_medio_var44_hace3,saldo_medio_var44_ult1,saldo_medio_var44_ult3,var38,TARGET
0,1,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,39205.170000,0
1,3,2,34,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,49278.030000,0
2,4,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,67333.770000,0
3,8,2,37,0.0,195.0,195.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,64007.970000,0
4,10,2,39,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117310.979016,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76015,151829,2,48,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,60926.490000,0
76016,151830,2,39,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,118634.520000,0
76017,151835,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,74028.150000,0
76018,151836,2,25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,84278.160000,0
76019,151838,2,46,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117310.979016,0

In [156]:
traindataset2.describe()

,ID,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var40_comer_ult1,imp_op_var40_comer_ult3,imp_op_var40_efect_ult1,imp_op_var40_efect_ult3,...,saldo_medio_var33_hace2,saldo_medio_var33_hace3,saldo_medio_var33_ult1,saldo_medio_var33_ult3,saldo_medio_var44_hace2,saldo_medio_var44_hace3,saldo_medio_var44_ult1,saldo_medio_var44_ult3,var38,TARGET
count,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,...,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,76020.000000,7.602000e+04,76020.000000
mean,75964.050723,-1523.199277,33.212865,86.208265,72.363067,119.529632,3.559130,6.472698,0.412946,0.567352,...,7.935824,1.365146,12.215580,8.784074,31.505324,1.858575,76.026165,56.614351,1.172358e+05,0.039569
std,43781.947379,39033.462364,12.956486,1614.757313,339.315831,546.266294,93.155749,153.737066,30.604864,36.513513,...,455.887218,113.959637,783.207399,538.439211,2013.125393,147.786584,4040.337842,2852.579397,1.826646e+05,0.194945
min,1.000000,-999999.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.163750e+03,0.000000
25%,38104.750000,2.000000,23.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.787061e+04,0.000000
50%,76043.000000,2.000000,28.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.064092e+05,0.000000
75%,113748.750000,2.000000,40.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.187563e+05,0.000000
max,151838.000000,238.000000,105.000000,210000.000000,12888.030000,21024.810000,8237.820000,11073.570000,6600.000000,6600.000000,...,50003.880000,20385.720000,138831.630000,91778.730000,438329.220000,24650.010000,681462.900000,397884.300000,2.203474e+07,1.000000

In [157]:
traindataset2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 76020 entries, 0 to 76019
Columns: 371 entries, ID to TARGET
dtypes: float64(111), int64(260)
memory usage: 215.2 MB

In [159]:
x_traindataset2=traindataset2.drop(columns=["TARGET"])

In [160]:
x_traindataset2.shape

(76020, 370)

In [162]:
y_traindataset2=traindataset2["TARGET"]

In [210]:
#Without OVERSAMPLING checking the accuray and Classification_report
xtrain2,xtest2,ytrain2,ytest2=train_test_split(x_traindataset2,y_traindataset2)

In [211]:
from sklearn.linear_model import LogisticRegression

In [212]:
model=LogisticRegression()

In [213]:
model.fit(xtrain2,ytrain2)

LogisticRegression()

In [215]:
model.score(xtest2,ytest2)

0.959010786635096

In [163]:
from collections import Counter
Counter(y_traindataset2)

Counter({0: 73012, 1: 3008})

In [164]:
majo0=traindataset2[traindataset2['TARGET']==0]

In [165]:
majo0.shape

(73012, 371)

In [216]:
majority1=majo0.sample(3008)

In [217]:
majority1.shape

(3008, 371)

In [222]:
mino0=traindataset2[traindataset2['TARGET']==1]

In [223]:
mino0.shape

(3008, 371)

In [227]:
final1=pd.concat([majority1,mino0],axis=0)

In [228]:
from sklearn.ensemble import RandomForestClassifier
model2=RandomForestClassifier()

In [229]:
final1

,ID,var3,var15,imp_ent_var16_ult1,imp_op_var39_comer_ult1,imp_op_var39_comer_ult3,imp_op_var40_comer_ult1,imp_op_var40_comer_ult3,imp_op_var40_efect_ult1,imp_op_var40_efect_ult3,...,saldo_medio_var33_hace2,saldo_medio_var33_hace3,saldo_medio_var33_ult1,saldo_medio_var33_ult3,saldo_medio_var44_hace2,saldo_medio_var44_hace3,saldo_medio_var44_ult1,saldo_medio_var44_ult3,var38,TARGET
56454,112635,2,30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,72163.140000,0
22519,45105,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117310.979016,0
27228,54507,2,27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,67347.870000,0
43360,86860,2,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,37440.660000,0
41019,82113,2,27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117310.979016,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75902,151601,2,30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,45742.470000,1
75917,151634,2,27,0.0,378.0,378.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,183437.250000,1
75941,151679,2,26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,69111.870000,1
76000,151804,2,75,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,117310.979016,1
76007,151811,2,61,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,83667.150000,1

In [250]:
x_final1=final1.drop(columns=["TARGET","ID"])
y_final1=final1["TARGET"]

In [251]:
fxtrain,fxtest,fytrain,fytest=train_test_split(x_final1,y_final1,test_size=0.20)
model2.fit(fxtrain,fytrain)

RandomForestClassifier()

In [252]:
model2.score(fxtest,fytest)

0.7308970099667774

In [253]:
model21=LogisticRegression()

In [254]:
model21.fit(fxtrain,fytrain)

LogisticRegression()

In [255]:
model21.score(fxtest,fytest)

0.532392026578073

# Selecting best 25 feature

In [256]:
from genetic_selection import GeneticSelectionCV

In [257]:
Geneticmodel= DecisionTreeClassifier()
GENETIC = GeneticSelectionCV(
    Geneticmodel, cv=5, verbose=0,
    scoring="accuracy", max_features=29,
    n_population=100, crossover_proba=0.5,
    mutation_proba=0.2, n_generations=100,
    crossover_independent_proba=0.5,
    mutation_independent_proba=0.04,
    tournament_size=3, n_gen_no_change=10,
    caching=True, n_jobs=-1)
Geneticmodel = GENETIC.fit(fxtrain,fytrain)

In [259]:
GENETIC.score(fxtest,fytest)

0.6985049833887044

In [260]:
print(GENETIC.get_support())

#Get column names
cols = GENETIC.get_support(indices=True) #get column indices
print("\n cols = ", cols, "\n")

features_df_new_ga = fxtrain.iloc[:,cols] #Get cols of X-Train with col names
print(features_df_new_ga.shape)
print ("\n features_df_new_ga= ", features_df_new_ga)

[False  True False False False False False False False False False False
 False False  True False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False  True  True  True False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
  True False False False False False False  True False False False False
 False False False False False False False  True False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False  True False False False False False
 False False False False False False False False False False False False
 False False False False  True False False False False False False False
 False False False False False False False False False False False  True
 False False False False False False False False False False  True False
 False False False False False False False False False False False  True
 False False False False False False False False False False False False
 False False  True  True False False False False False False False False
 False False False False False False False False False False  True False
 False False False False False False False False  True False False False
 False False False False False False False False False False False False
 False False False False False  True False False False False False False
 False False  True False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False  True False
 False False False False False False False False False False False False
 False  True False False False False False False False False False False
 False False False  True False  True False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False]

 cols =  [  1  14  56  57  58  84  91 103 138 160 179 190 203 218 219 238 248 269
 278 310 325 339 341]

(4812, 23)

 features_df_new_ga=         var15  imp_op_var41_ult1  ind_var27_0  ind_var28_0  ind_var28  \
4839      43               0.00            0            0          0
21039     28               0.00            0            0          0
59070     48             228.39            0            0          0
12248     63               0.00            0            0          0
41133     23               0.00            0            0          0
...      ...                ...          ...          ...        ...
25315     22               0.00            0            0          0
45851     34               0.00            0            0          0
27681     37               0.00            0            0          0
71910     25               0.00            0            0          0
63128     42               0.00            0            0          0

       ind_var46_0  num_var6_0  num_var13_medio  num_var30  num_var44  ...  \
4839             0           0                0          0          0  ...
21039            0           0                0          0          0  ...
59070            0           0                0          3          0  ...
12248            0           0                0          3          0  ...
41133            0           0                0          3          0  ...
...            ...         ...              ...        ...        ...  ...
25315            0           0                0          3          0  ...
45851            0           0                0          0          0  ...
27681            0           0                0          3          0  ...
71910            0           0                0          3          0  ...
63128            0           0                0          0          0  ...

       delta_num_trasp_var33_out_1y3  delta_num_venta_var44_1y3  \
4839                               0                        0.0
21039                              0                        0.0
59070                              0                        0.0
12248                              0                        0.0
41133                              0                        0.0
...                              ...                        ...
25315                              0                        0.0
45851                              0                        0.0
27681                              0                        0.0
71910                              0                        0.0
63128                              0                        0.0

       imp_reemb_var33_hace3  imp_trasp_var33_out_hace3  num_var7_emit_ult1  \
4839                       0                          0                   0
21039                      0                          0                   0
59070                      0                          0                   0
12248                      0                          0                   0
41133                      0                          0                   0
...                      ...                        ...                 ...
25315                      0                          0                   0
45851                      0                          0                   0
27681                      0                          0                   0
71910                      0                          0                   0
63128                      0                          0                   0

       num_med_var22_ult3  num_var43_emit_ult1  num_var45_ult1  \
4839                    0                    0               0
21039                   0                    0               0
59070                   0                    3              18
12248                   0                    0               0
41133                   0                    0               0
...                   ...                  ...             ...
25315                   0                    0               0
45851                   0                    0               0
27681                   0                    0               0
71910                   0                    0               0
63128                   0                    0               0

       saldo_medio_var12_ult3  saldo_medio_var13_corto_hace3
4839                     0.00                            0.0
21039                    0.00                            0.0
59070                    0.00                            0.0
12248                36436.41                            0.0
41133                    0.00                            0.0
...                       ...                            ...
25315                    0.00                            0.0
45851                    0.00                            0.0
27681                    0.00                            0.0
71910                    0.00                            0.0
63128                    0.00                            0.0

[4812 rows x 23 columns]

In [261]:
cols

array([  1,  14,  56,  57,  58,  84,  91, 103, 138, 160, 179, 190, 203,
       218, 219, 238, 248, 269, 278, 310, 325, 339, 341], dtype=int64)

In [262]:
features_df_new_ga

,var15,imp_op_var41_ult1,ind_var27_0,ind_var28_0,ind_var28,ind_var46_0,num_var6_0,num_var13_medio,num_var30,num_var44,...,delta_num_trasp_var33_out_1y3,delta_num_venta_var44_1y3,imp_reemb_var33_hace3,imp_trasp_var33_out_hace3,num_var7_emit_ult1,num_med_var22_ult3,num_var43_emit_ult1,num_var45_ult1,saldo_medio_var12_ult3,saldo_medio_var13_corto_hace3
4839,43,0.00,0,0,0,0,0,0,0,0,...,0,0.0,0,0,0,0,0,0,0.00,0.0
21039,28,0.00,0,0,0,0,0,0,0,0,...,0,0.0,0,0,0,0,0,0,0.00,0.0
59070,48,228.39,0,0,0,0,0,0,3,0,...,0,0.0,0,0,0,0,3,18,0.00,0.0
12248,63,0.00,0,0,0,0,0,0,3,0,...,0,0.0,0,0,0,0,0,0,36436.41,0.0
41133,23,0.00,0,0,0,0,0,0,3,0,...,0,0.0,0,0,0,0,0,0,0.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25315,22,0.00,0,0,0,0,0,0,3,0,...,0,0.0,0,0,0,0,0,0,0.00,0.0
45851,34,0.00,0,0,0,0,0,0,0,0,...,0,0.0,0,0,0,0,0,0,0.00,0.0
27681,37,0.00,0,0,0,0,0,0,3,0,...,0,0.0,0,0,0,0,0,0,0.00,0.0
71910,25,0.00,0,0,0,0,0,0,3,0,...,0,0.0,0,0,0,0,0,0,0.00,0.0
63128,42,0.00,0,0,0,0,0,0,0,0,...,0,0.0,0,0,0,0,0,0,0.00,0.0

In [264]:
model4=RandomForestClassifier()

In [265]:
new_test_GA=fxtest.iloc[:,cols]

In [266]:
new_test_GA.shape

(1204, 23)

In [267]:
model4.fit(features_df_new_ga,fytrain)

RandomForestClassifier()

In [268]:
model4.score(new_test_GA,fytest)

0.7300664451827242

# Hyperparameter tuning on best selected 25 top features

In [270]:
from sklearn.model_selection import RandomizedSearchCV
mi=RandomForestClassifier()
param_grid = { 

     'max_features': ['sqrt', 'log2'],
    'max_depth' : [4,5,6,7,8],
    'criterion' :['gini', 'entropy']
}
hypermodel= RandomizedSearchCV(estimator=mi,param_distributions=param_grid ,cv= 5)
hypermodel.fit(features_df_new_ga,fytrain)

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(),
                   param_distributions={'criterion': ['gini', 'entropy'],
                                        'max_depth': [4, 5, 6, 7, 8],
                                        'max_features': ['sqrt', 'log2']})

In [271]:
hypermodel.score(new_test_GA,fytest)

0.7416943521594684

# TOP 50 COLUMNS using gradient algorithm

In [273]:
Geneticmodel50= DecisionTreeClassifier()
GENETIC50 = GeneticSelectionCV(
    Geneticmodel50, cv=5, verbose=0,
    scoring="accuracy", max_features=50,
    n_population=100, crossover_proba=0.5,
    mutation_proba=0.2, n_generations=100,
    crossover_independent_proba=0.5,
    mutation_independent_proba=0.04,
    tournament_size=3, n_gen_no_change=10,
    caching=True, n_jobs=-1)
Geneticmodel50 = GENETIC50.fit(fxtrain,fytrain)

In [278]:
top_50 = GENETIC50.get_support(indices=True)
top_50_feature = fxtrain.iloc[:,top_50]

In [280]:
#This are top 50 columns 
top_50_feature.columns

Index(['var15', 'imp_op_var39_comer_ult1', 'imp_op_var40_efect_ult3',
       'imp_op_var39_ult1', 'ind_var12_0', 'ind_var13_corto_0',
       'ind_var13_medio', 'ind_var19', 'ind_var24_0', 'ind_var25_cte',
       'ind_var33_0', 'ind_var39', 'ind_var44', 'num_var5_0',
       'num_var13_medio', 'num_var26_0', 'num_var26', 'num_op_var39_ult3',
       'num_var27', 'num_var33', 'num_var37_med_ult2', 'num_var41',
       'saldo_var27', 'saldo_var30', 'saldo_var41',
       'delta_imp_compra_var44_1y3', 'imp_amort_var34_hace3',
       'imp_aport_var13_hace3', 'imp_aport_var13_ult1', 'imp_aport_var33_ult1',
       'imp_var7_recib_ult1', 'imp_reemb_var17_hace3', 'ind_var7_recib_ult1',
       'num_aport_var17_hace3', 'num_med_var45_ult3', 'num_reemb_var17_ult1',
       'num_reemb_var33_ult1', 'num_trasp_var17_out_ult1',
       'num_trasp_var33_in_ult1', 'num_trasp_var33_out_ult1', 'num_var45_ult1',
       'saldo_medio_var12_hace2', 'saldo_medio_var13_largo_ult3',
       'saldo_medio_var13_medio_hace3', 'saldo_medio_var17_ult3',
       'saldo_medio_var33_hace2'],
      dtype='object')

# TOP 25 columns using SelectKBest

In [288]:
from sklearn.feature_selection import SelectFromModel
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2, f_classif

In [289]:
feature_25= SelectKBest(f_classif, k=25)
feature_25.fit(fxtrain,fytrain)
feature_25_index = feature_25.get_support(True)
print ("feature index_25 =", feature_25_index)

feature index_25 = [  1  24  27  29  31  32  33  38  63  88  90  93  97  98  99 104 138 147
 158 171 182 193 263 280 283]

In [290]:
feature_25_index = feature_25.fit_transform(fxtrain,fytrain)
print(feature_25_index.shape)

feature_25_dataset= pd.DataFrame(feature_25_index)
print(feature_25_dataset)

(4812, 25)
        0    1    2    3    4    5    6    7    8    9   ...   15   16   17  \
0     43.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0
1     28.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0
2     48.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  2.0  ...  0.0  3.0  9.0
3     63.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  ...  0.0  3.0  3.0
4     23.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  ...  0.0  3.0  3.0
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
4807  22.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  ...  0.0  3.0  3.0
4808  34.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0
4809  37.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  ...  0.0  3.0  3.0
4810  25.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  ...  0.0  3.0  3.0
4811  42.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0

       18   19        20    21   22   23   24
0     0.0  0.0      0.00  99.0  0.0  0.0  0.0
1     0.0  0.0      0.00  99.0  0.0  0.0  0.0
2     3.0  0.0     47.61   1.0  0.0  3.0  0.0
3     3.0  0.0  60792.66   2.0  0.0  1.0  0.0
4     3.0  0.0     90.00   2.0  0.0  2.0  0.0
...   ...  ...       ...   ...  ...  ...  ...
4807  3.0  0.0     90.00   3.0  0.0  3.0  0.0
4808  0.0  0.0      0.00  99.0  0.0  0.0  0.0
4809  3.0  0.0    450.00   3.0  0.0  3.0  0.0
4810  3.0  0.0      3.00   3.0  0.0  3.0  0.0
4811  0.0  0.0      0.00  99.0  0.0  0.0  0.0

[4812 rows x 25 columns]

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
0,43.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.00,99.0,0.0,0.0,0.0
1,28.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.00,99.0,0.0,0.0,0.0
2,48.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,...,0.0,3.0,9.0,3.0,0.0,47.61,1.0,0.0,3.0,0.0
3,63.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.0,3.0,3.0,3.0,0.0,60792.66,2.0,0.0,1.0,0.0
4,23.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.0,3.0,3.0,3.0,0.0,90.00,2.0,0.0,2.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4807,22.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.0,3.0,3.0,3.0,0.0,90.00,3.0,0.0,3.0,0.0
4808,34.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.00,99.0,0.0,0.0,0.0
4809,37.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.0,3.0,3.0,3.0,0.0,450.00,3.0,0.0,3.0,0.0
4810,25.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,...,0.0,3.0,3.0,3.0,0.0,3.00,3.0,0.0,3.0,0.0
4811,42.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.00,99.0,0.0,0.0,0.0

In [291]:
feature_50= SelectKBest(f_classif, k=50)
feature_50.fit(fxtrain,fytrain)
feature_50_index = feature_50.get_support(True)
print ("feature index_25 =", feature_50_index)

feature index_25 = [  1  12  13  14  15  16  17  23  24  27  28  29  30  31  32  33  38  48
  49  63  88  89  90  93  94  96  97  98  99 104 113 114 138 147 158 168
 171 182 193 224 263 280 281 282 283 331 340 342 343 368]

In [ ]:
feature_25_index = feature_25.fit_transform(fxtrain,fytrain)
print(feature_25_index.shape)

feature_25_dataset= pd.DataFrame(feature_25_index)
print(feature_25_dataset)