In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from matplotlib import pyplot as plt

In [2]:
dataset=pd.read_csv(r"C:\Users\ggomare\Downloads\Melbourne_housing_FULL.csv")

In [3]:
dataset

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2,h,NaN,SS,Jellis,3/09/2016,2.5,3067.0,...,1.0,1.0,126.0,NaN,NaN,Yarra City Council,-37.80140,144.99580,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra City Council,-37.79960,144.99840,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra City Council,-37.80790,144.99340,Northern Metropolitan,4019.0
3,Abbotsford,18/659 Victoria St,3,u,NaN,VB,Rounds,4/02/2016,2.5,3067.0,...,2.0,1.0,0.0,NaN,NaN,Yarra City Council,-37.81140,145.01160,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra City Council,-37.80930,144.99440,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,Yarraville,13 Burns St,4,h,1480000.0,PI,Jas,24/02/2018,6.3,3013.0,...,1.0,3.0,593.0,NaN,NaN,Maribyrnong City Council,-37.81053,144.88467,Western Metropolitan,6543.0
34853,Yarraville,29A Murray St,2,h,888000.0,SP,Sweeney,24/02/2018,6.3,3013.0,...,2.0,1.0,98.0,104.0,2018.0,Maribyrnong City Council,-37.81551,144.88826,Western Metropolitan,6543.0
34854,Yarraville,147A Severn St,2,t,705000.0,S,Jas,24/02/2018,6.3,3013.0,...,1.0,2.0,220.0,120.0,2000.0,Maribyrnong City Council,-37.82286,144.87856,Western Metropolitan,6543.0
34855,Yarraville,12/37 Stephen St,3,h,1140000.0,SP,hockingstuart,24/02/2018,6.3,3013.0,...,NaN,NaN,NaN,NaN,NaN,Maribyrnong City Council,NaN,NaN,Western Metropolitan,6543.0
34856,Yarraville,3 Tarrengower St,2,h,1020000.0,PI,RW,24/02/2018,6.3,3013.0,...,1.0,0.0,250.0,103.0,1930.0,Maribyrnong City Council,-37.81810,144.89351,Western Metropolitan,6543.0

In [4]:
dataset.isnull().sum()

Suburb               0
Address              0
Rooms                0
Type                 0
Price             7610
Method               0
SellerG              0
Date                 0
Distance             1
Postcode             1
Bedroom2          8217
Bathroom          8226
Car               8728
Landsize         11810
BuildingArea     21115
YearBuilt        19306
CouncilArea          3
Lattitude         7976
Longtitude        7976
Regionname           3
Propertycount        3
dtype: int64

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34857 entries, 0 to 34856
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         34857 non-null  object
 1   Address        34857 non-null  object
 2   Rooms          34857 non-null  int64
 3   Type           34857 non-null  object
 4   Price          27247 non-null  float64
 5   Method         34857 non-null  object
 6   SellerG        34857 non-null  object
 7   Date           34857 non-null  object
 8   Distance       34856 non-null  float64
 9   Postcode       34856 non-null  float64
 10  Bedroom2       26640 non-null  float64
 11  Bathroom       26631 non-null  float64
 12  Car            26129 non-null  float64
 13  Landsize       23047 non-null  float64
 14  BuildingArea   13742 non-null  float64
 15  YearBuilt      15551 non-null  float64
 16  CouncilArea    34854 non-null  object
 17  Lattitude      26881 non-null  float64
 18  Longtitude     26881 non-null  float64
 19  Regionname     34854 non-null  object
 20  Propertycount  34854 non-null  float64
dtypes: float64(12), int64(1), object(8)
memory usage: 5.6+ MB

In [6]:
dataset.Suburb.value_counts()

Reservoir          844
Bentleigh East     583
Richmond           552
Glen Iris          491
Preston            485
                  ...
Belgrave             1
Cranbourne East      1
Yarra Glen           1
Olinda               1
Menzies Creek        1
Name: Suburb, Length: 351, dtype: int64

In [7]:
dataset.Type.unique()

array(['h', 'u', 't'], dtype=object)

In [8]:
dataset.describe()

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,34857.000000,2.724700e+04,34856.000000,34856.000000,26640.000000,26631.000000,26129.000000,23047.000000,13742.00000,15551.000000,26881.000000,26881.000000,34854.000000
mean,3.031012,1.050173e+06,11.184929,3116.062859,3.084647,1.624798,1.728845,593.598993,160.25640,1965.289885,-37.810634,145.001851,7572.888306
std,0.969933,6.414671e+05,6.788892,109.023903,0.980690,0.724212,1.010771,3398.841946,401.26706,37.328178,0.090279,0.120169,4428.090313
min,1.000000,8.500000e+04,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.00000,1196.000000,-38.190430,144.423790,83.000000
25%,2.000000,6.350000e+05,6.400000,3051.000000,2.000000,1.000000,1.000000,224.000000,102.00000,1940.000000,-37.862950,144.933500,4385.000000
50%,3.000000,8.700000e+05,10.300000,3103.000000,3.000000,2.000000,2.000000,521.000000,136.00000,1970.000000,-37.807600,145.007800,6763.000000
75%,4.000000,1.295000e+06,14.000000,3156.000000,4.000000,2.000000,2.000000,670.000000,188.00000,2000.000000,-37.754100,145.071900,10412.000000
max,16.000000,1.120000e+07,48.100000,3978.000000,30.000000,12.000000,26.000000,433014.000000,44515.00000,2106.000000,-37.390200,145.526350,21650.000000

In [9]:
dataset.Type.replace({
    'h':1, 
    'u':2,
    't':3
},inplace=True)

In [10]:
dataset

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2,1,NaN,SS,Jellis,3/09/2016,2.5,3067.0,...,1.0,1.0,126.0,NaN,NaN,Yarra City Council,-37.80140,144.99580,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2,1,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra City Council,-37.79960,144.99840,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2,1,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra City Council,-37.80790,144.99340,Northern Metropolitan,4019.0
3,Abbotsford,18/659 Victoria St,3,2,NaN,VB,Rounds,4/02/2016,2.5,3067.0,...,2.0,1.0,0.0,NaN,NaN,Yarra City Council,-37.81140,145.01160,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3,1,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra City Council,-37.80930,144.99440,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,Yarraville,13 Burns St,4,1,1480000.0,PI,Jas,24/02/2018,6.3,3013.0,...,1.0,3.0,593.0,NaN,NaN,Maribyrnong City Council,-37.81053,144.88467,Western Metropolitan,6543.0
34853,Yarraville,29A Murray St,2,1,888000.0,SP,Sweeney,24/02/2018,6.3,3013.0,...,2.0,1.0,98.0,104.0,2018.0,Maribyrnong City Council,-37.81551,144.88826,Western Metropolitan,6543.0
34854,Yarraville,147A Severn St,2,3,705000.0,S,Jas,24/02/2018,6.3,3013.0,...,1.0,2.0,220.0,120.0,2000.0,Maribyrnong City Council,-37.82286,144.87856,Western Metropolitan,6543.0
34855,Yarraville,12/37 Stephen St,3,1,1140000.0,SP,hockingstuart,24/02/2018,6.3,3013.0,...,NaN,NaN,NaN,NaN,NaN,Maribyrnong City Council,NaN,NaN,Western Metropolitan,6543.0
34856,Yarraville,3 Tarrengower St,2,1,1020000.0,PI,RW,24/02/2018,6.3,3013.0,...,1.0,0.0,250.0,103.0,1930.0,Maribyrnong City Council,-37.81810,144.89351,Western Metropolitan,6543.0

In [11]:
dataset.Method.unique()

array(['SS', 'S', 'VB', 'SP', 'PI', 'SN', 'W', 'PN', 'SA'], dtype=object)

In [12]:
dataset

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2,1,NaN,SS,Jellis,3/09/2016,2.5,3067.0,...,1.0,1.0,126.0,NaN,NaN,Yarra City Council,-37.80140,144.99580,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2,1,1480000.0,S,Biggin,3/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra City Council,-37.79960,144.99840,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2,1,1035000.0,S,Biggin,4/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra City Council,-37.80790,144.99340,Northern Metropolitan,4019.0
3,Abbotsford,18/659 Victoria St,3,2,NaN,VB,Rounds,4/02/2016,2.5,3067.0,...,2.0,1.0,0.0,NaN,NaN,Yarra City Council,-37.81140,145.01160,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3,1,1465000.0,SP,Biggin,4/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra City Council,-37.80930,144.99440,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,Yarraville,13 Burns St,4,1,1480000.0,PI,Jas,24/02/2018,6.3,3013.0,...,1.0,3.0,593.0,NaN,NaN,Maribyrnong City Council,-37.81053,144.88467,Western Metropolitan,6543.0
34853,Yarraville,29A Murray St,2,1,888000.0,SP,Sweeney,24/02/2018,6.3,3013.0,...,2.0,1.0,98.0,104.0,2018.0,Maribyrnong City Council,-37.81551,144.88826,Western Metropolitan,6543.0
34854,Yarraville,147A Severn St,2,3,705000.0,S,Jas,24/02/2018,6.3,3013.0,...,1.0,2.0,220.0,120.0,2000.0,Maribyrnong City Council,-37.82286,144.87856,Western Metropolitan,6543.0
34855,Yarraville,12/37 Stephen St,3,1,1140000.0,SP,hockingstuart,24/02/2018,6.3,3013.0,...,NaN,NaN,NaN,NaN,NaN,Maribyrnong City Council,NaN,NaN,Western Metropolitan,6543.0
34856,Yarraville,3 Tarrengower St,2,1,1020000.0,PI,RW,24/02/2018,6.3,3013.0,...,1.0,0.0,250.0,103.0,1930.0,Maribyrnong City Council,-37.81810,144.89351,Western Metropolitan,6543.0

In [13]:
dataset.columns

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

In [14]:
use_column=["Suburb","Rooms","Type","Method","SellerG",
            "Regionname","Propertycount","Distance","CouncilArea",
           "Bedroom2","Bathroom","Car","Landsize","BuildingArea","Price"]

In [15]:
dataset1=dataset[use_column]

In [16]:
dataset1

,Suburb,Rooms,Type,Method,SellerG,Regionname,Propertycount,Distance,CouncilArea,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Price
0,Abbotsford,2,1,SS,Jellis,Northern Metropolitan,4019.0,2.5,Yarra City Council,2.0,1.0,1.0,126.0,NaN,NaN
1,Abbotsford,2,1,S,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,2.0,1.0,1.0,202.0,NaN,1480000.0
2,Abbotsford,2,1,S,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,2.0,1.0,0.0,156.0,79.0,1035000.0
3,Abbotsford,3,2,VB,Rounds,Northern Metropolitan,4019.0,2.5,Yarra City Council,3.0,2.0,1.0,0.0,NaN,NaN
4,Abbotsford,3,1,SP,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,3.0,2.0,0.0,134.0,150.0,1465000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,Yarraville,4,1,PI,Jas,Western Metropolitan,6543.0,6.3,Maribyrnong City Council,4.0,1.0,3.0,593.0,NaN,1480000.0
34853,Yarraville,2,1,SP,Sweeney,Western Metropolitan,6543.0,6.3,Maribyrnong City Council,2.0,2.0,1.0,98.0,104.0,888000.0
34854,Yarraville,2,3,S,Jas,Western Metropolitan,6543.0,6.3,Maribyrnong City Council,2.0,1.0,2.0,220.0,120.0,705000.0
34855,Yarraville,3,1,SP,hockingstuart,Western Metropolitan,6543.0,6.3,Maribyrnong City Council,NaN,NaN,NaN,NaN,NaN,1140000.0
34856,Yarraville,2,1,PI,RW,Western Metropolitan,6543.0,6.3,Maribyrnong City Council,2.0,1.0,0.0,250.0,103.0,1020000.0

In [17]:
dataset1.isnull().sum()

Suburb               0
Rooms                0
Type                 0
Method               0
SellerG              0
Regionname           3
Propertycount        3
Distance             1
CouncilArea          3
Bedroom2          8217
Bathroom          8226
Car               8728
Landsize         11810
BuildingArea     21115
Price             7610
dtype: int64

In [18]:
dataset1.describe()

,Rooms,Type,Propertycount,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Price
count,34857.000000,34857.000000,34854.000000,34856.000000,26640.000000,26631.000000,26129.000000,23047.000000,13742.00000,2.724700e+04
mean,3.031012,1.414752,7572.888306,11.184929,3.084647,1.624798,1.728845,593.598993,160.25640,1.050173e+06
std,0.969933,0.669445,4428.090313,6.788892,0.980690,0.724212,1.010771,3398.841946,401.26706,6.414671e+05
min,1.000000,1.000000,83.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,8.500000e+04
25%,2.000000,1.000000,4385.000000,6.400000,2.000000,1.000000,1.000000,224.000000,102.00000,6.350000e+05
50%,3.000000,1.000000,6763.000000,10.300000,3.000000,2.000000,2.000000,521.000000,136.00000,8.700000e+05
75%,4.000000,2.000000,10412.000000,14.000000,4.000000,2.000000,2.000000,670.000000,188.00000,1.295000e+06
max,16.000000,3.000000,21650.000000,48.100000,30.000000,12.000000,26.000000,433014.000000,44515.00000,1.120000e+07

In [19]:
colu_fillna=["Bedroom2","Car","Propertycount","Bathroom","Distance"]

In [20]:
dataset1[colu_fillna]=dataset1[colu_fillna].fillna(0)

C:\Users\ggomare\AppData\Local\Temp\ipykernel_16608\2269519228.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset1[colu_fillna]=dataset1[colu_fillna].fillna(0)

In [21]:
dataset1.isnull().sum()

Suburb               0
Rooms                0
Type                 0
Method               0
SellerG              0
Regionname           3
Propertycount        0
Distance             0
CouncilArea          3
Bedroom2             0
Bathroom             0
Car                  0
Landsize         11810
BuildingArea     21115
Price             7610
dtype: int64

In [22]:
dataset1["Landsize"]=dataset1["Landsize"].fillna(dataset1.Landsize.mean())

C:\Users\ggomare\AppData\Local\Temp\ipykernel_16608\966651421.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset1["Landsize"]=dataset1["Landsize"].fillna(dataset1.Landsize.mean())

In [23]:
import warnings
warnings.filterwarnings("ignore")

In [24]:
dataset1["BuildingArea"]=dataset1["BuildingArea"].fillna(dataset1.BuildingArea.mean())

In [25]:
dataset1["Price"]=dataset1["Price"].fillna(dataset1.Price.mean())

In [26]:
dataset1

,Suburb,Rooms,Type,Method,SellerG,Regionname,Propertycount,Distance,CouncilArea,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Price
0,Abbotsford,2,1,SS,Jellis,Northern Metropolitan,4019.0,2.5,Yarra City Council,2.0,1.0,1.0,126.000000,160.2564,1.050173e+06
1,Abbotsford,2,1,S,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,2.0,1.0,1.0,202.000000,160.2564,1.480000e+06
2,Abbotsford,2,1,S,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,2.0,1.0,0.0,156.000000,79.0000,1.035000e+06
3,Abbotsford,3,2,VB,Rounds,Northern Metropolitan,4019.0,2.5,Yarra City Council,3.0,2.0,1.0,0.000000,160.2564,1.050173e+06
4,Abbotsford,3,1,SP,Biggin,Northern Metropolitan,4019.0,2.5,Yarra City Council,3.0,2.0,0.0,134.000000,150.0000,1.465000e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,Yarraville,4,1,PI,Jas,Western Metropolitan,6543.0,6.3,Maribyrnong City Council,4.0,1.0,3.0,593.000000,160.2564,1.480000e+06
34853,Yarraville,2,1,SP,Sweeney,Western Metropolitan,6543.0,6.3,Maribyrnong City Council,2.0,2.0,1.0,98.000000,104.0000,8.880000e+05
34854,Yarraville,2,3,S,Jas,Western Metropolitan,6543.0,6.3,Maribyrnong City Council,2.0,1.0,2.0,220.000000,120.0000,7.050000e+05
34855,Yarraville,3,1,SP,hockingstuart,Western Metropolitan,6543.0,6.3,Maribyrnong City Council,0.0,0.0,0.0,593.598993,160.2564,1.140000e+06
34856,Yarraville,2,1,PI,RW,Western Metropolitan,6543.0,6.3,Maribyrnong City Council,2.0,1.0,0.0,250.000000,103.0000,1.020000e+06

In [27]:
dataset1["SellerG"].unique()

array(['Jellis', 'Biggin', 'Rounds', 'Nelson', 'Collins', 'Dingle',
       'Purplebricks', 'Greg', 'Philip', 'LITTLE', 'Kay', 'Beller',
       'Marshall', 'hockingstuart', 'Brad', 'Maddison', 'Barry',
       'Airport', 'Considine', 'Rendina', 'Ray', 'Propertyau', 'McDonald',
       'Frank', 'Prof.', 'Harcourts', 'Thomson', 'Buxton', 'RT',
       "Sotheby's", 'Cayzer', 'Chisholm', 'McGrath', 'Brace', 'Miles',
       'Holland', 'Love', 'Thomas', 'Barlow', 'Sweeney', 'Village', 'Jas',
       'Williams', 'Gunn&Co', 'Burnham', 'Point', 'Compton', 'FN',
       'Hunter', 'Raine&Horne', 'Noel', 'Hodges', 'Gary', 'Fletchers',
       'Woodards', 'Raine', 'Alexkarbon', 'Walshe', 'Weda', 'Stockdale',
       'Tim', 'Buxton/Marshall', 'AIME', 'Moonee', 'HAR', 'Edward', 'RW',
       'North', 'MICM', 'Ascend', 'Christopher', 'Morrison', 'Bekdon',
       'Mandy', 'R&H', 'Fletchers/One', 'Lindellas', 'Appleby', 'Assisi',
       'One', 'Owen', 'Parkes', 'C21', 'Century', "O'Brien", 'Bayside',
       'Anderson', 'Paul', 'hockingstuart/Buxton', 'Smart', 'First',
       'Matthew', 'Melbourne', 'Nick', 'Allens', 'Bells', 'Nguyen',
       'Trimson', 'Douglas', 'Batty', 'GL', 'YPA', "Tiernan's", 'J',
       'Castran', 'Branon', 'Rodney', 'Joseph', 'Harrington', 'Galldon',
       'Grantham', 'Chambers', 'Pagan', 'Peter',
       'hockingstuart/Advantage', 'Ross', 'Rayner', 'Garvey',
       "O'Donoghues", 'Hamilton', 'Weast', 'Kelly', 'Property',
       "Private/Tiernan's", 'Australian', 'Bustin', "Abercromby's",
       'Whiting', 'iTRAK', 'Del', 'Caine', 'Nicholson', 'JMRE', 'ASL',
       'Changing', 'Re', 'RE', 'Walsh', 'Foxtons', 'Ham', 'Darren', 'Vic',
       'Haughton', 'Scott', 'Pride', 'Morleys', 'Wilson',
       'Buxton/Advantage', 'Professionals', 'Joe', 'Red',
       'hockingstuart/Jellis', 'Craig', 'Naison', 'Sweeney/Advantage',
       'Reach', 'Domain', 'Eview', 'Jason', "D'Aprano", 'Charlton',
       'CASTRAN', 'Wood', 'William', 'Coventry', 'Buckingham', 'Nardella',
       'Karen', 'LJ', 'Shape', 'Direct', 'Fletchers/Fletchers', 'Besser',
       'Johnston', 'Avion', 'Redina', 'Clairmont', 'Lucas', 'Dixon',
       'Xynergy', 'Elite', 'Buxton/Find', 'W.B.', 'Leased',
       'Harcourts/Barry', 'Win', 'Collings', 'New', 'Parkinson', 'Geoff',
       'hockingstuart/Barry', 'Blue', 'MSM', 'Steveway',
       'hockingstuart/Village', 'VICPROP', 'Inner', 'Meadows', 'Allan',
       'S&L', 'Crane', 'Calder', 'Metro', 'Homes', 'Zahn', 'Mason',
       'Landfield', 'David', 'Luxe', 'Prowse', 'Ken', 'Rombotis', 'iOne',
       'hockingstuart/Sweeney', 'Iconek', 'Luxton', 'Hooper', 'JRW',
       'Oak', 'White', 'Jim', 'Weston', '@Realty', 'Reed', 'Oriental',
       'Max', 'Steller', 'Rosin', 'Real', 'Jeffrey', 'Hall', 'Icon',
       'buyMyplace', 'WHITEFOX', 'Christou', 'Marvelli', "Grant's",
       'Hoskins', 'Gardiner', 'McLennan', 'Triwest', 'Reliance',
       'PRDNationwide', 'Only', 'Leyton', 'iSell', 'Obrien', 'Maitland',
       'Millership', 'L', 'Emerson', 'Follett', 'Ash', 'LLC', 'Ace',
       'Flannagan', 'Carter', 'WeSell', 'M.J', 'iProperty',
       'Hayeswinckle', 'Schroeder', 'iHomes', 'VICProp', 'REMAX', 'Space',
       'Victory', 'Aumeca', 'Mindacom', 'Ryder', 'Sanctuary', 'Leeburn',
       'Asset', 'Westside', 'Sell', 'Mitchell', 'Darras', 'U', 'Nicholas',
       'Rexhepi', 'Keatings', 'Aquire', 'Conquest', 'Prime', 'Donovan',
       'Community', 'Free', 'Veitch', 'John', 'Peake', 'Ristic', 'JY',
       'Upper', 'Daniel', 'VicHomes', 'TRUE', 'McNaughton', 'Leading',
       'Bullen', 'Better', 'Boutique', 'Royston', 'Langwell', 'Silver',
       'Wyndham', 'Kaye', 'Nicholls', 'Bowman', 'Just', 'Home', 'Le',
       'Cooper', 'Black', 'The', 'Open', 'Roger', 'McEwing', 'Sandhurst',
       'Boran', 'hockingstuart/hockingstuart', 'Area', 'MJ', 'Eric', 'SN',
       'Waterfront', 'P', 'PRD', 'Bombay', 'Quinta', 'T', 'Tanner', 'LJH',
       'Munn', 'Knight', 'Justin', 'Blackbird', 'Sweeney/Burnham', 'H',
       'Alex', 'Can', 'Pavilion', 'Benchmark', 'Gellibrand',
       'hockingstuart/Harcourts', 'Charter', 'Surreal', 'Vicprop', 'A',
       'Upside', 'OBrien', 'Meallin', 'Malvern', 'Mark', 'Bradly', 'For',
       'Peninsula', 'Sutherland', 'Leaders', 'Spencer',
       'McGrath/Langwell', 'Benlor', 'Burns', 'Sterling', 'K.R.Peters',
       'Buxton/Buxton', 'CarlinSmith', 'Gold', 'Hill', 'People',
       'hockingstuart/Biggin', 'Mega', 'Skad', 'Ruralco', 'Create',
       'Janice', 'R', 'G&H', 'Commercial', 'PSP', 'hockingstuart/Cayzer',
       'Unity', 'Sprint', 'McGrath/Buxton', 'hockingstuart/Marshall',
       'McGrath/First', 'voglwalpole', 'Watermark', 'Methven'],
      dtype=object)

In [28]:
dataset2=pd.get_dummies(dataset1,drop_first=True)

In [29]:
dataset2.shape

(34857, 794)

In [35]:
dataset2

,Rooms,Type,Propertycount,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,Price,...,CouncilArea_Moorabool Shire Council,CouncilArea_Moreland City Council,CouncilArea_Nillumbik Shire Council,CouncilArea_Port Phillip City Council,CouncilArea_Stonnington City Council,CouncilArea_Whitehorse City Council,CouncilArea_Whittlesea City Council,CouncilArea_Wyndham City Council,CouncilArea_Yarra City Council,CouncilArea_Yarra Ranges Shire Council
0,2,1,4019.0,2.5,2.0,1.0,1.0,126.000000,160.2564,1.050173e+06,...,0,0,0,0,0,0,0,0,1,0
1,2,1,4019.0,2.5,2.0,1.0,1.0,202.000000,160.2564,1.480000e+06,...,0,0,0,0,0,0,0,0,1,0
2,2,1,4019.0,2.5,2.0,1.0,0.0,156.000000,79.0000,1.035000e+06,...,0,0,0,0,0,0,0,0,1,0
3,3,2,4019.0,2.5,3.0,2.0,1.0,0.000000,160.2564,1.050173e+06,...,0,0,0,0,0,0,0,0,1,0
4,3,1,4019.0,2.5,3.0,2.0,0.0,134.000000,150.0000,1.465000e+06,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,4,1,6543.0,6.3,4.0,1.0,3.0,593.000000,160.2564,1.480000e+06,...,0,0,0,0,0,0,0,0,0,0
34853,2,1,6543.0,6.3,2.0,2.0,1.0,98.000000,104.0000,8.880000e+05,...,0,0,0,0,0,0,0,0,0,0
34854,2,3,6543.0,6.3,2.0,1.0,2.0,220.000000,120.0000,7.050000e+05,...,0,0,0,0,0,0,0,0,0,0
34855,3,1,6543.0,6.3,0.0,0.0,0.0,593.598993,160.2564,1.140000e+06,...,0,0,0,0,0,0,0,0,0,0
34856,2,1,6543.0,6.3,2.0,1.0,0.0,250.000000,103.0000,1.020000e+06,...,0,0,0,0,0,0,0,0,0,0

In [30]:
dataset2.isnull().sum()

Rooms                                     0
Type                                      0
Propertycount                             0
Distance                                  0
Bedroom2                                  0
                                         ..
CouncilArea_Whitehorse City Council       0
CouncilArea_Whittlesea City Council       0
CouncilArea_Wyndham City Council          0
CouncilArea_Yarra City Council            0
CouncilArea_Yarra Ranges Shire Council    0
Length: 794, dtype: int64

In [31]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso
from sklearn.linear_model import Ridge

In [32]:
x=dataset2.drop("Price",axis=1)
y=dataset2["Price"]

In [33]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.20)

In [34]:
model1=LinearRegression()

In [53]:
model1.fit(xtrain,ytrain)

LinearRegression()

In [54]:
model1.score(xtest,ytest)

0.38244173391389213

In [55]:
model1.score(xtrain,ytrain)

0.46992276123902776

In [78]:
model2=Lasso(alpha=50,max_iter=100,tol=0.1)

In [79]:
model2.fit(xtrain,ytrain)

Lasso(alpha=50, max_iter=100, tol=0.1)

In [80]:
model2.score(xtrain,ytrain)

0.46439620068604825

In [81]:
model2.score(xtest,ytest)

0.382627105543505

In [82]:
model3=Ridge(alpha=50,max_iter=100,tol=0.1)

In [83]:
model3.fit(xtrain,ytrain)

Ridge(alpha=50, max_iter=100, tol=0.1)

In [84]:
model3.score(xtest,ytest)

0.3735959595250876